package com.airbnb.android.showkase.processor.writer

import com.airbnb.android.showkase.processor.writer.ShowkaseBrowserWriter.Companion.SHOWKASE_MODELS_PACKAGE_NAME
import com.airbnb.android.showkase.processor.writer.ShowkaseBrowserWriter.Companion.SHOWKASE_PROVIDER_CLASS_NAME
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.ksp.addOriginatingKSFile
import com.squareup.kotlinpoet.ksp.writeTo

internal class ShowkaseExtensionFunctionsWriter(
    private val codeGenerator: CodeGenerator
) {
    enum class Target { ANDROID, COMMON }

    internal fun generateShowkaseExtensionFunctions(
        rootModulePackageName: String,
        rootModuleClassName: String,
        rootElement: KSClassDeclaration,
        target: Target = Target.ANDROID,
    ) {
        val fileName = when (target) {
            Target.ANDROID -> "${rootModuleClassName}$SHOWKASE_METHODS_SUFFIX"
            Target.COMMON -> "${rootModuleClassName}$COMMON_SHOWKASE_METHODS_SUFFIX"
        }
        val fileBuilder = getFileBuilder(rootModulePackageName, fileName).apply {
            if (target == Target.ANDROID) {
                addFunction(
                    generateIntentFunction(
                        rootModulePackageName,
                        rootModuleClassName,
                        rootElement
                    )
                )
            }
            addFunction(
                generateMetadataFunction(
                    rootElement = rootElement,
                    classKey = "$rootModulePackageName.$rootModuleClassName",
                    codegenClassName = ClassName(
                        rootModulePackageName,
                        "${rootModuleClassName}Codegen"
                    ),
                    target = target,
                )
            )
        }

        rootElement.containingFile?.let { fileBuilder.addFileComment("").build() }
        val built = fileBuilder.build()
        // Originating files for FunSpecs are picked up via the FileSpec automatically when
        // FunSpec.Builder.addOriginatingKSFile is used.
        built.writeTo(codeGenerator, aggregating = true)
    }

    private fun generateIntentFunction(
        rootModulePackageName: String,
        rootModuleClassName: String,
        rootElement: KSClassDeclaration,
    ) = FunSpec.builder(INTENT_FUNCTION_NAME).apply {
        addParameter(
            CONTEXT_PARAMETER_NAME, CONTEXT_CLASS_NAME
        )
        addKdoc("Helper function that's autogenerated and gives you an intent to start the " +
                "ShowkaseBrowser.")
        receiver(SHOWKASE_OBJECT_CLASS_NAME)
        returns(INTENT_CLASS_NAME)
        addCode(
            CodeBlock.Builder()
                .indent()
                .addStatement(
                    "val intent = %T(%L, %T::class.java)",
                    INTENT_CLASS_NAME,
                    CONTEXT_PARAMETER_NAME,
                    SHOWKASE_BROWSER_ACTIVITY_CLASS_NAME
                )
                .addStatement(
                    "intent.putExtra(%S, %S)",
                    SHOWKASE_ROOT_MODULE_KEY,
                    "$rootModulePackageName.$rootModuleClassName"
                )
                .addStatement(
                    "return intent"
                )
                .unindent()
                .build()
        )
        rootElement.containingFile?.let { addOriginatingKSFile(it) }
    }
        .build()

    private fun generateMetadataFunction(
        rootElement: KSClassDeclaration,
        classKey: String,
        codegenClassName: ClassName,
        target: Target,
    ) = FunSpec.builder(METADATA_FUNCTION_NAME).apply {
        receiver(SHOWKASE_OBJECT_CLASS_NAME)
        returns(SHOWKASE_ELEMENTS_METADATA_CLASS_NAME)
        addKdoc("Helper function that's give's you access to Showkase metadata. This contains " +
                "data about the composables, colors and typography in your codebase that's " +
                "rendered in showkase.")
        when (target) {
            Target.ANDROID -> {
                val errorMessage =
                    "The class wasn't generated correctly. Make sure that you have " +
                            "setup Showkase correctly by following the steps here - " +
                            "https://github.com/airbnb/Showkase#Installation."
                addCode(
                    CodeBlock.Builder()
                        .indent()
                        .addStatement("try {")
                        .indent()
                        .addStatement(
                            "val showkaseComponentProvider = Class.forName(\"${classKey}Codegen\")\n\t" +
                                    ".getDeclaredConstructor()\n\t" +
                                    ".newInstance() as %T",
                            SHOWKASE_PROVIDER_CLASS_NAME
                        )
                        .addStatement("return %L.metadata()", "showkaseComponentProvider")
                        .unindent()
                        .addStatement("} catch(exception: ClassNotFoundException) {")
                        .indent()
                        .addStatement("error(%S)", errorMessage)
                        .unindent()
                        .addStatement("}")
                        .unindent()
                        .build()
                )
            }

            Target.COMMON -> {
                // Generated codegen class lives in the same package — call its constructor
                // directly. This avoids JVM-only reflection so the helper compiles on
                // Kotlin/Native targets.
                addCode(
                    CodeBlock.builder()
                        .addStatement("return %T().metadata()", codegenClassName)
                        .build()
                )
            }
        }
        rootElement.containingFile?.let { addOriginatingKSFile(it) }
    }
        .build()

    companion object {
        private const val SHOWKASE_ROOT_MODULE_KEY = "SHOWKASE_ROOT_MODULE"
        private const val INTENT_FUNCTION_NAME = "getBrowserIntent"
        private const val METADATA_FUNCTION_NAME = "getMetadata"
        private const val SHOWKASE_EXTENSION_FUNCTIONS_NAME = "ShowkaseExtensionFunctions"
        private const val SHOWKASE_METHODS_SUFFIX = "${SHOWKASE_EXTENSION_FUNCTIONS_NAME}Codegen"
        private const val COMMON_SHOWKASE_METHODS_SUFFIX =
            "Common${SHOWKASE_EXTENSION_FUNCTIONS_NAME}Codegen"
        private const val CONTEXT_PARAMETER_NAME = "context"
        private const val CONTEXT_PACKAGE_NAME = "android.content"
        internal val CONTEXT_CLASS_NAME =
            ClassName(CONTEXT_PACKAGE_NAME, "Context")
        private val INTENT_CLASS_NAME =
            ClassName(CONTEXT_PACKAGE_NAME, "Intent")
        private val SHOWKASE_BROWSER_ACTIVITY_CLASS_NAME =
            ClassName("com.airbnb.android.showkase.ui", "ShowkaseBrowserActivity")
        private val SHOWKASE_ELEMENTS_METADATA_CLASS_NAME =
            ClassName(SHOWKASE_MODELS_PACKAGE_NAME, "ShowkaseElementsMetadata")
        internal val SHOWKASE_OBJECT_CLASS_NAME =
            ClassName(SHOWKASE_MODELS_PACKAGE_NAME, "Showkase")
    }
}
